---
title: "Leaflet Project"
author: "KMMKhalid"
date: "January 31, 2019"
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)

```

## My Travel Log

I traveled for quite a bit in 2018. The map shows the places I've been to and how long I stayed in each. Zoom in for the location details.

```{r, echo=FALSE}

Loc <- c("Marawi City, Lanao del Sur, PH",
         "Quezon City, Metro Manila, PH", 
         "Berkeley, California, US",
         "Iligan City, Lanao del Norte, PH", 
         "Cagayan De Oro City, Misamis Oriental, PH",
         "San Jose Del Monte, Bulacan, PH",
         "Los Banos, Laguna, PH",
         "Tagaytay, Rizal, PH",
         "Taipei, TW",
         "San Francisco, California, US",
         "Muir Woods National Monument, California, US",
         "Pleasanton, California, US", 
         "Oakland, California, US",
         "Bangkok, TH",
         "Chiang Mai, TH",
         "Oroquieta City, Misamis Occidental, PH",
         "Cebu City, PH")

Lat <- c(8.010621, 
         14.676208, 
         37.8715926,
         8.25, 
         8.48222, 
         14.8205675, 
         14.1699121, 
         14.115286, 
         25.0329636,
         37.7749295, 
         37.89702, 
         37.662431, 
         37.8043637,
         13.736717,
         18.796143,
         8.4833314,
         10.31672)

Lng <- c(124.297718, 
         121.043861,
         -122.2727469,
         124.4, 
         124.64722, 
         121.1022942, 
         121.244063, 
         120.962116, 
         121.5654268, 
         -122.4194155, 
         -122.581118, 
         -121.874679, 
         -122.2711137,
          100.523186,
         98.979263,
         123.7999968,
         123.89071)


df <- data.frame(Loc, Lat, Lng)



house_icon <- makeIcon(iconUrl = "http://icon-park.com/imagefiles/location_map_pin_blue10.png", iconWidth = 25, iconHeight = 25, iconAnchorX = 0, iconAnchorY = 0)

temp_icon1 <- makeIcon(iconUrl = "http://icon-park.com/imagefiles/location_map_pin_red10.png", iconWidth = 25, iconHeight = 25, iconAnchorX = 0, iconAnchorY = 0)
temp_icon2 <- makeIcon(iconUrl = "http://icon-park.com/imagefiles/location_map_pin_yellow10.png", iconWidth = 25, iconHeight = 25, iconAnchorX = 0, iconAnchorY = 0)

```

## My Map

```{r, echo=FALSE}
library(leaflet)
my_map <- leaflet() %>%
  addTiles('https://server.arcgisonline.com/ArcGIS/rest/services/NatGeo_World_Map/MapServer/tile/{z}/{y}/{x}', attribution = 'Tiles Courtesy of National Geographic, Esri, DeLorme, NAVTEQ, UNEP-WCMC, USGS, NASA, ESA, METI, NRCAN, GEBCO, NOAA, iPC') %>%
   addMarkers(data = df[1:3,], lat= ~Lat, lng= ~Lng, popup= ~Loc, icon = house_icon) %>%
  #addMarkers(data = df[1:3,], lat= ~Lat, lng= ~Lng, popup= ~Places_Visited, icon = house_icon, clusterOptions = markerClusterOptions()) %>%
  addMarkers(data = df[4:7,], lat= ~Lat, lng= ~Lng, popup= ~Loc, icon = temp_icon1) %>%
  addMarkers(data = df[8:17,], lat= ~Lat, lng= ~Lng, popup= ~Loc, icon = temp_icon2) %>%
  addLegend(labels = c("More than a Month", "Less than a Month","Less than a Week"), position = "topright", colors = c("blue", "red", "yellow"), title = "Trip Duration")

  
my_map
```
